---
- name: DEPLOY AS3 DEC
  hosts: localhost
  connection: local
  gather_facts: no


  vars:
  
  vars_files:
  - ../creds/bigip_cred.yaml

  tasks:


- name: Create an AS3 Declaration
  uri:
    url: https://18.134.162.22/mgmt/shared/appsvcs/declare
    user: "{{ bigip_user }}"
    password: "{{ bigip_pass }}"
    method: POST
    body: "{{ lookup('file','issue.json') }}"
    force_basic_auth: yes
    status_code: 200
    body_format: json
    validate_cert: no


...